binance:
  api_key: ""
  api_secret: ""
  recv_window: 5000
  proxy:
    enabled: false
    host: "127.0.0.1"
    port: 7890

dingding:
  enabled: true
  token: ""
  token2: ""

trade:
  ma_x: 5
  ma_y: 60
  kLine_type: '15m'
  binance_market: "SPOT"
  binance_coinBase: "USDT"
  binance_coinBase_count: 20
  binance_tradeCoin: "DOGE"
  isOpenSellStrategy: true
  sellStrategy1:
    profit: 1.05
    sell: 0.1
  sellStrategy2:
    profit: 1.10
    sell: 0.2
  sellStrategy3:
    profit: 1.20
    sell: 0.2

mysql:
  enabled: true
  host: "localhost"
  port: 3306
  user: "root"
  password: "rootroot"
  database: "smart_quant_robot"
  charset: "utf8mb4"